import test from "node:test";
import assert from "node:assert/strict";
import { randomBytes } from "node:crypto";
import { accountStateKey, blockDisplayId, decodeContinuumId, encodeContinuumId, isPaymentAddress, NOVA_REALM_ID, suggestSingleSymbolCorrections, transactionDisplayId, validatorDisplayId } from "../src/continuum-address.mjs";

test("NCA round-trips a stable 256-bit Account ID",()=>{const identifier=randomBytes(32),address=encodeContinuumId(identifier),decoded=decodeContinuumId(address,{type:"account"});assert.match(address,/^nva-m-a1-/);assert.equal(decoded.network,"mainnet");assert.equal(decoded.version,1);assert.deepEqual(decoded.identifier,identifier);assert.deepEqual(decoded.realmId,NOVA_REALM_ID);assert.equal(isPaymentAddress(address),true)});
test("NCA network and object types are visibly and cryptographically separated",()=>{const identifier=randomBytes(32),account=encodeContinuumId(identifier,{network:"testnet"}),validator=validatorDisplayId(account),transaction=transactionDisplayId(identifier.toString("hex")),block=blockDisplayId(identifier.toString("hex"));assert.match(account,/^nva-t-a1-/);assert.match(validator,/^nva-t-v1-/);assert.match(transaction,/^nva-m-x1-/);assert.match(block,/^nva-m-b1-/);assert.equal(isPaymentAddress(validator),false);assert.equal(isPaymentAddress(transaction),false)});
test("NCA rejects transcription, grouping, casing and realm corruption",()=>{const address=encodeContinuumId(randomBytes(32)),position=address.lastIndexOf("-")+2,replacement=address[position]==="0"?"2":"0",corrupt=`${address.slice(0,position)}${replacement}${address.slice(position+1)}`;assert.equal(isPaymentAddress(corrupt),false);assert.equal(isPaymentAddress(address.toUpperCase()),false);assert.equal(isPaymentAddress(address.replace("-","")),false);assert.throws(()=>decodeContinuumId(address.replace("nva-m-","nva-t-")),/network mismatch/)});
test("NCA can locate a single-symbol typo but never auto-corrects it",()=>{const address=encodeContinuumId(randomBytes(32)),position=address.length-3,replacement=address[position]==="0"?"2":"0",corrupt=`${address.slice(0,position)}${replacement}${address.slice(position+1)}`,suggestions=suggestSingleSymbolCorrections(corrupt);assert.ok(suggestions.includes(address));assert.equal(isPaymentAddress(corrupt),false)});
test("text renderings resolve to a format-independent internal state key",()=>{const identifier=randomBytes(32),mainnet=encodeContinuumId(identifier),testnet=encodeContinuumId(identifier,{network:"testnet"});assert.equal(accountStateKey(mainnet),accountStateKey(testnet));assert.match(accountStateKey(mainnet),/^a:[a-f0-9]{64}$/)});
