const CHARSET="qpzry9x8gf2tvdw0s3jn54khce6mua7l",CHARSET_MAP=new Map([...CHARSET].map((character,index)=>[character,index])),BECH32M=0x2bc830a3;
const polymod=values=>{let checksum=1;for(const value of values){const top=checksum>>>25;checksum=((checksum&0x1ffffff)<<5)^value;for(let index=0;index<5;index++)if((top>>>index)&1)checksum^=[0x3b6a57b2,0x26508e6d,0x1ea119fa,0x3d4233dd,0x2a1462b3][index]}return checksum>>>0};
const expandHrp=hrp=>[...[...hrp].map(character=>character.charCodeAt(0)>>>5),0,...[...hrp].map(character=>character.charCodeAt(0)&31)];
const checksum=(hrp,data)=>{const value=polymod([...expandHrp(hrp),...data,0,0,0,0,0,0])^BECH32M;return Array.from({length:6},(_,index)=>(value>>>(5*(5-index)))&31)};
export const convertBits=(values,fromBits,toBits,pad)=>{let accumulator=0,bits=0;const result=[],maxValue=(1<<toBits)-1,maxAccumulator=(1<<(fromBits+toBits-1))-1;for(const value of values){if(value<0||(value>>fromBits)!==0)throw new Error("invalid address data range");accumulator=((accumulator<<fromBits)|value)&maxAccumulator;bits+=fromBits;while(bits>=toBits){bits-=toBits;result.push((accumulator>>>bits)&maxValue)}}if(pad){if(bits)result.push((accumulator<<(toBits-bits))&maxValue)}else if(bits>=fromBits||((accumulator<<(toBits-bits))&maxValue)!==0)throw new Error("invalid address padding");return result};
export function encodeBech32m(hrp,data){if(!/^[a-z0-9]{1,20}$/.test(hrp))throw new Error("invalid address prefix");const words=[...data,...checksum(hrp,data)],encoded=`${hrp}1${words.map(value=>CHARSET[value]).join("")}`;if(encoded.length>90)throw new Error("address exceeds Bech32m length limit");return encoded}
export function decodeBech32m(address){if(typeof address!=="string"||address.length<8||address.length>90||address!==address.toLowerCase())throw new Error("invalid Bech32m casing or length");const separator=address.lastIndexOf("1");if(separator<1||separator+7>address.length)throw new Error("invalid Bech32m separator");const hrp=address.slice(0,separator),data=[...address.slice(separator+1)].map(character=>{const value=CHARSET_MAP.get(character);if(value===undefined)throw new Error("invalid Bech32m character");return value});if(polymod([...expandHrp(hrp),...data])!==BECH32M)throw new Error("invalid Bech32m checksum");return{hrp,data:data.slice(0,-6)}}
export function encodeAccountId(identifier,{testnet=false}={}){const bytes=Buffer.from(identifier);if(bytes.length!==32)throw new Error("NOVA Account ID requires 256 bits");return encodeBech32m(testnet?"tnova":"nova",convertBits([1,...bytes],8,5,true))}
export function decodeAccountId(address){const{hrp,data}=decodeBech32m(address);if(hrp!=="nova"&&hrp!=="tnova")throw new Error("unsupported NOVA account prefix");const decoded=Buffer.from(convertBits(data,5,8,false));if(decoded.length!==33||decoded[0]!==1)throw new Error("unsupported NOVA address version");return{network:hrp==="nova"?"mainnet":"testnet",version:decoded[0],identifier:decoded.subarray(1)}}
export function isAccountId(address){try{decodeAccountId(address);return true}catch{return false}}
const encodeTypedId=(prefix,bytes)=>encodeBech32m(prefix,convertBits([1,...bytes],8,5,true));
export function validatorDisplayId(accountId){const decoded=decodeAccountId(accountId);return encodeTypedId(decoded.network==="mainnet"?"novaval":"tnovaval",decoded.identifier)}
export function transactionDisplayId(hash){if(!/^[a-f0-9]{64}$/.test(hash))throw new Error("transaction hash must contain 256 bits");return encodeTypedId("novatx",Buffer.from(hash,"hex"))}
export function blockDisplayId(hash){if(!/^[a-f0-9]{64}$/.test(hash))throw new Error("block hash must contain 256 bits");return encodeTypedId("novablk",Buffer.from(hash,"hex"))}
