import { createServer } from "node:http";
import { existsSync, readFileSync, renameSync, unlinkSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { NovaChain } from "./core.mjs";
import { verifyPayload } from "./crypto.mjs";
import { formatNova } from "./emission.mjs";

const dataDir=resolve(process.env.NOVA_DATA_DIR??".nova"),config=JSON.parse(readFileSync(join(dataDir,"network.json"),"utf8")),host=process.env.NOVA_RPC_HOST??config.host??"127.0.0.1",port=Number(process.env.NOVA_RPC_PORT??config.port),peers=(process.env.NOVA_PEERS??config.peers.join(",")).split(",").filter(Boolean),chain=new NovaChain(dataDir).load(),validatorKey=JSON.parse(readFileSync(join(dataDir,"keys","validator.json"),"utf8")),votesPath=join(dataDir,"votes.json"),pendingPath=join(dataDir,"pending-proposal.json");
let votes=existsSync(votesPath)?JSON.parse(readFileSync(votesPath,"utf8")):{},pendingProposal=existsSync(pendingPath)?JSON.parse(readFileSync(pendingPath,"utf8")):null,proposing=false;
const encode=value=>JSON.stringify(value,null,2),reply=(response,status,value)=>{response.writeHead(status,{"content-type":"application/json; charset=utf-8","cache-control":"no-store"});response.end(encode(value))},readBody=request=>new Promise((resolveBody,reject)=>{let raw="";request.on("data",chunk=>{raw+=chunk;if(raw.length>2_000_000)reject(new Error("request body too large"))});request.on("end",()=>{try{resolveBody(JSON.parse(raw||"{}"))}catch{reject(new Error("invalid JSON"))}});request.on("error",reject)}),post=async(url,path,value,headers={})=>{const response=await fetch(`${url}${path}`,{method:"POST",headers:{"content-type":"application/json",...headers},body:JSON.stringify(value),signal:AbortSignal.timeout(2500)});const body=await response.json();if(!response.ok)throw new Error(body.error??`peer ${response.status}`);return body};
const validatorOrder=()=>Object.keys(chain.state.validators).sort(),expectedProposer=height=>validatorOrder()[(height-1)%validatorOrder().length];
const persistVote=(height,hash)=>{const current=votes[String(height)];if(current&&current!==hash)throw new Error("double-sign protection: conflicting proposal");votes[String(height)]=hash;const temp=`${votesPath}.tmp`;writeFileSync(temp,encode(votes));renameSync(temp,votesPath)};
const verifyProposerProof=block=>{const proof=block.certificate.signatures.find(item=>item.validatorId===block.header.proposerId),validator=chain.state.validators[block.header.proposerId],vote={chainId:block.header.chainId,height:block.header.height,blockHash:block.hash,stateRoot:block.header.stateRoot};if(!proof||!validator||!verifyPayload(vote,proof.signature,validator.publicKey))throw new Error("proposal lacks valid proposer proof")};
const signProposal=block=>{if(block.header.proposerId!==expectedProposer(block.header.height))throw new Error("proposal violates deterministic proposer schedule");if(block.header.proposerId!==validatorKey.accountId)verifyProposerProof(block);const signature=chain.signBlockProposal(block,validatorKey);persistVote(block.header.height,block.hash);return signature};
const acceptCommit=block=>{if(block.header.height<=chain.state.height){const known=chain.block(block.header.height);if(known?.hash===block.hash)return{alreadyCommitted:true,height:chain.state.height};throw new Error("conflicting committed block")};chain.importBlock(block);if(pendingProposal?.header.height<=chain.state.height){pendingProposal=null;if(existsSync(pendingPath))unlinkSync(pendingPath)}return{committed:true,height:chain.state.height,hash:block.hash}};

const server=createServer(async(request,response)=>{try{const url=new URL(request.url??"/","http://nova.local");
  if(request.method==="GET"&&url.pathname==="/health")return reply(response,200,{ok:true,chainId:chain.state.chainId,height:chain.state.height,validatorId:validatorKey.accountId,peers:peers.length});
  if(request.method==="GET"&&url.pathname==="/status")return reply(response,200,{chainId:chain.state.chainId,height:chain.state.height,latestBlock:chain.state.lastBlockHash,validatorId:validatorKey.accountId,expectedProposer:expectedProposer(chain.state.height+1),supply:{...chain.state.supply,totalNova:formatNova(chain.state.supply.total)},mempool:chain.mempool.length});
  if(request.method==="GET"&&url.pathname.startsWith("/account/")){const id=decodeURIComponent(url.pathname.slice(9)),account=chain.account(id);return account?reply(response,200,{accountId:id,...account,balanceNova:formatNova(account.balance)}):reply(response,404,{error:"account_not_found"})}
  if(request.method==="GET"&&url.pathname.startsWith("/block/")){const block=chain.block(Number(url.pathname.slice(7)));return block?reply(response,200,block):reply(response,404,{error:"block_not_found"})}
  if(request.method==="POST"&&url.pathname==="/tx"){const tx=await readBody(request),txId=chain.submit(tx);if(request.headers["x-nova-forwarded"]!=="1")await Promise.allSettled(peers.map(peer=>post(peer,"/tx",tx,{"x-nova-forwarded":"1"})));return reply(response,202,{accepted:true,txId})}
  if(request.method==="POST"&&url.pathname==="/consensus/proposal"){const block=await readBody(request);return reply(response,200,{signature:signProposal(block)})}
  if(request.method==="POST"&&url.pathname==="/consensus/commit"){const block=await readBody(request);return reply(response,200,acceptCommit(block))}
  return reply(response,404,{error:"not_found"});
}catch(error){return reply(response,400,{error:error instanceof Error?error.message:"request_failed"})}});

async function consensusTick(){if(proposing||expectedProposer(chain.state.height+1)!==validatorKey.accountId)return;const now=Math.floor(Date.now()/1000);if(now<chain.state.lastTimestamp+chain.state.epochSeconds)return;proposing=true;try{const block=pendingProposal?.header.height===chain.state.height+1?pendingProposal:chain.buildBlockProposal(validatorKey,now);if(!pendingProposal){const proposerProof=signProposal(block);block.certificate.signatures=[proposerProof];pendingProposal=block;writeFileSync(pendingPath,encode(block))}block.certificate.signatures=[block.certificate.signatures[0]];const signatures=[block.certificate.signatures[0]],responses=await Promise.allSettled(peers.map(peer=>post(peer,"/consensus/proposal",block)));for(const result of responses)if(result.status==="fulfilled")signatures.push(result.value.signature);block.certificate.signatures=signatures;chain.verifyBlockCertificate(block);acceptCommit(block);await Promise.allSettled(peers.map(peer=>post(peer,"/consensus/commit",block)));console.log(`committed height=${block.header.height} hash=${block.hash.slice(0,16)} votes=${signatures.length}`)}catch(error){console.error(`consensus height=${chain.state.height+1} failed: ${error.message}`)}finally{proposing=false}}
server.listen(port,host,()=>console.log(`NOVA validator ${validatorKey.accountId} listening on http://${host}:${port} peers=${peers.length}`));const timer=setInterval(consensusTick,500),shutdown=()=>{clearInterval(timer);server.close(()=>process.exit(0))};process.on("SIGINT",shutdown);process.on("SIGTERM",shutdown);
